apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      # Set here your Gitlab Registry address
      - name: webapp
        image: registry.gitlab.com/ricardoblucas/surfsail-predict:<VERSION>
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "500Mi"
          requests:
            cpu: "250m"
            memory: "250Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          timeoutSeconds: 5
          initialDelaySeconds: 60
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          timeoutSeconds: 5
          initialDelaySeconds: 60
      restartPolicy: Always
      # Secret needed to access to Gitlab Registry from EKS
      imagePullSecrets:
        - name: gitlab
status: {}